In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
#membaca dataset dari file ke pandas dataFrame
dataset= pd.read_csv('data.csv', delimiter=',', header=0)

In [3]:
dataset.head()

male  age  education  currentSmoker  ...    BMI  heartRate  glucose  TenYearCHD
0     1   39        4.0              0  ...  26.97       80.0     77.0           0
1     0   46        2.0              0  ...  28.73       95.0     76.0           0
2     1   48        1.0              1  ...  25.34       75.0     70.0           0
3     0   61        3.0              1  ...  28.58       65.0    103.0           1
4     0   46        3.0              1  ...  23.10       85.0     85.0           0

[5 rows x 16 columns]

In [4]:
dataset = dataset.drop(labels="age", axis=1)
dataset = dataset.drop(labels="education", axis=1)
dataset = dataset.drop(labels="cigsPerDay", axis=1)
dataset = dataset.drop(labels="BPMeds", axis=1)
dataset = dataset.drop(labels="totChol", axis=1)
dataset = dataset.drop(labels="sysBP", axis=1)
dataset = dataset.drop(labels="diaBP", axis=1)
dataset = dataset.drop(labels="BMI", axis=1)
dataset = dataset.drop(labels="heartRate", axis=1)
dataset = dataset.drop(labels="glucose", axis=1)
dataset

male  currentSmoker  prevalentStroke  prevalentHyp  diabetes  TenYearCHD
0        1              0                0             0         0           0
1        0              0                0             0         0           0
2        1              1                0             0         0           0
3        0              1                0             1         0           1
4        0              1                0             0         0           0
...    ...            ...              ...           ...       ...         ...
4233     1              1                0             1         0           1
4234     1              1                0             0         0           0
4235     0              1                0             0         0           0
4236     0              1                0             0         0           0
4237     0              0                0             0         0           0

[4238 rows x 6 columns]

In [5]:
dataset = dataset.to_numpy()

In [6]:
print(dataset)

[[1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 0 0 0 0]
 ...
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]


In [7]:
#membagi dataset => 1059 baris data untuk training dan 3179 baris data untuk testing
dataTraining = np.concatenate((dataset[0:529, :], dataset[529:1059, :]),axis=0)
dataTesting = np.concatenate((dataset[1059:2119, :], dataset[2119:4238, :]),axis=0)

In [8]:
print(dataTraining)
len(dataTraining)

[[1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 0 0 0 0]
 ...
 [1 0 0 0 0 0]
 [1 1 0 1 0 0]
 [0 0 0 1 0 1]]


1059

In [9]:
print(dataTesting)
len(dataTesting)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 ...
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]


3179

In [10]:
#memecah dataset ke input data dan label
inputTraining = dataTraining[:, 0:5]
inputTesting = dataTesting[:, 0:5]
labelTraining = dataTraining[:, 5]
labelTesting = dataTesting[:, 5]
print(labelTraining)
len(labelTraining)

[0 0 0 ... 0 0 1]


1059

In [11]:
#mendefinisikan decission tree classifier
model = tree.DecisionTreeClassifier()

In [12]:
#mentraining model
model = model.fit(inputTraining, labelTraining)

In [13]:
#memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ",labelTesting)
print("HasilPrediksi : ",hasilPrediksi)

Label Sebenarnya :  [0 0 0 ... 0 0 0]
HasilPrediksi :  [0 0 0 ... 0 0 0]


In [14]:
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, "data")
print("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar :  2709 data
Prediksi Salah :  470 data
Akurasi :  85.21547656495754 %
